### PR TITLE
Use bytedeco ffmpeg for saving videos

### PR DESCRIPTION
**Pull request by hamoid**
Draft. Testing to see if we can use the ffmpeg binary provided by bytedeco instead of user-provided ones.

Tested succesfully on one Linux machine. Needs testing on other OSes.

### CODE REVIEW

**Comment by hamoid** [comment]
Does it work on exported applications?

**Comment by edwinRNDR** [comment]
Will need to verify this on macos

**Comment by edwinRNDR** [comment]
It appears the ffmpeg binary that is bundled for macos (x64) does not come with a libx264 codec.  The videos produced with libopenh264 are of a lesser quality than those produced with libx264. I am also not sure what other features may be missing? I think it is best to offer it as a last resort option, so after trying to locate ffmpeg in other locations.

Order in which to use ffmpeg:
1. ffmpeg in -Dorg.openrndr.ffmpeg=<path-to-ffmpeg-binary> , or ffmpeg in jar if set to "jar"
2. ffmpeg in cwd
3. ffmpeg on path
4. ffmpeg in jar, switch to libopenh264, issue warning

**Comment by edwinRNDR** [comment]
> It appears the ffmpeg binary that is bundled for macos (x64) does not come with a libx264 codec. The videos produced with libopenh264 are of a lesser quality than those produced with libx264. I am also not sure what other features may be missing? I think it is best to offer it as a last resort option, so after trying to locate ffmpeg in other locations.
> 
> Order in which to use ffmpeg:
> 
>     1. ffmpeg in `-Dorg.openrndr.ffmpeg=<path-to-ffmpeg-binary>` , or ffmpeg in jar if set to `jar`
> 
>     2. ffmpeg in cwd
> 
>     3. ffmpeg on path
> 
>     4. ffmpeg in jar, switch to libopenh264, issue warning

By switching to the right ffmpeg libraries (done in 8c5442dff5fdf5e27d0d103d5ede83db681b8762) we actually do have libx264. I'd still use the above scheme, except 4) no longer switches to libopenh264 and does not issue a warning.

**Comment by edwinRNDR** [comment]
awaiting the work in https://github.com/openrndr/openrndr/pull/365#issuecomment-1514419882 I converted the PR to a draft PR

**Comment by hamoid** [comment]
Verified that it works on my Linux machine.

- In openrndr, add `println(arguments)` to line 214 in `VideoWriter.kt` to make sure the -D argument works as expected
- Build openrndr
- Clone openrndr-template, use 0.4.4-SNAPSHOT
- Add `extend(ScreenRecorder()).also { it.maximumDuration = 5.0 }` to the template.

1. Run the template, prints `ffmpeg` (from path)
2. Add `-Dorg.openrndr.ffmpeg=jar` to VM options, uses built-in ffmpeg
3. Add `-Dorg.openrndr.ffmpeg=/usr/bin/ffmpeg` to VM options, uses provided ffmpeg
4. Copy ffmpeg into project folder, remove VM options, uses `./ffmpeg`

These steps should be tested on Windows and Mac.

**Comment by edwinRNDR** [comment]
@hamoid could you test if my latest commits work for you?

**Comment by hamoid** [comment]
I tested the 4 cases and they work on my Linux machine.

**Comment by edwinRNDR** [comment]
Great! I will test on macOS (Intel) today

**Comment by edwinRNDR** [comment]
Merging this but running ffmpeg from jar does not work on windows/macOS due to problems outlined in https://github.com/openrndr/openrndr/issues/379.

**Pull request merged**
