### PR TITLE
WIP Migrate to kts and fix dokka

### PR DESCRIPTION
**Pull request by hamoid**
Before this PR, our dokka configuration was no longer making use of the Module.md file.
This fixes it and uses one `include` Module.md per submodule. It also adds links on the API pages to GitHub via `sourceLink`.

The reason to split the file into one per project was to avoid recompilation of the whole documentation when the Module.md was changed, but I believe it did not help. Changing any of the Module.md files triggered a slow build. Merging the .md files back into one should be considered, although this split approach might be easier to maintain (in case a module is added or deleted).

This PR also converts the gradle files to kts, but only the parts required to make dokka work. The remaining tasks can be found under `PREVIOUS_GRADLE/build.gradle` and need to be converted to kotlin.

### CODE REVIEW

**Comment by hamoid** [comment]
I can close this one, right? @Vechro 

It sounds like you've been making all this happen in recent commits :-)

**Comment by Vechro** [comment]
I think we still don't have the Module.md files everywhere. Those would be nice.

**Comment by hamoid** [comment]
I see. Since you have this more in your head than I do (I tried doing this one year ago), maybe you want to see if there's relevant stuff around https://github.com/openrndr/openrndr/pull/254/files#diff-c0dfa6bc7a8685217f70a860145fbdf416d449eaff052fa28352c5cec1a98c06R85 ?

Maybe interesting are:
- `includes.from("Module.md")`
- `skipEmptyPackages.set(true)`
- The `dokkaIgnore` items?
- The `Module.md` files can be easily copied from this PR. They are not many. The content should be shown at the top of the documentation in each section. So far it's close to placeholder text, but we could add more details to them.

The GitHub links you added already :)

I don't know why some entries were repeated after line 49. Ah maybe that's for a root project and the other for sub-projects?

**Comment by Vechro** [comment]
Yeah the trickiest part with Dokka is applying its settings to all subprojects. I think I figured it out in #347 but I never managed to get it to apply the suppression settings with the regex, it just never worked, yet all the other settings applied fine, so I opted not to bother with that aspect. The `includes` seem pretty doable. `skipEmptyPackages` is actually true by default. I can try copying over the Module.md files at some point, perhaps keep the PR open till that time?

**Comment by edwinRNDR** [comment]
Most of this has find its way into OPENRNDR through the work of Vechro. Closing.

**Pull request closed without merging**
