### PR TITLE
Add geometry selection to Filter: Triangle or Quad

### PR DESCRIPTION
**Pull request by ricardomatias**
Based on [GCN Execution Patterns in Full Screen Passes)(https://michaldrobot.com/2014/04/01/gcn-execution-patterns-in-full-screen-passes/) and [Cat like coding](https://catlikecoding.com/unity/tutorials/scriptable-render-pipeline/post-processing/)

@edwinRNDR I'm unsure if GPUs nowadays perform optimizations for this special case and if so, whether there is a need to provide this option to the Filter.

### CODE REVIEW

**Comment by hamoid** [comment]
Hi! This sounds interesting... have you tried both cases? When would you use triangles and when quads?

**Comment by ricardomatias** [comment]
@hamoid I should have mentioned why I kept the Quad option. There's a parameter called `padding` which basically results in a shrunken quad (the shrinking is done inside the vertex shader) vs the color buffer where the effect is applied to. When you have the triangle geometry the "curtain drops" and you see a triangle.

Illustration:
padding-filter

**Comment by edwinRNDR** [comment]
Interesting. It looks better on paper but I am not sure if it makes a difference. Will evaluate this as it touches quite a bit of core functionality.

**Comment by hamoid** [comment]
So to confirm, this is about optimizing, right? 

The author of the first linked post reduced 0.1ms per frame in his use case, which was a 10% performance increase.

If I get it right, this is the relevant part from the second link:

> So Blit renders a quad made from two triangles. This works, but could be done in a more efficient way, by using a single triangle that cover the entire screen instead. The obvious benefit of that is the reduction of vertices and indices to three. However, the more significant difference is that it eliminates the diagonal where the two triangles of the quad meet. Because GPUs render fragments parallel in small blocks, some fragments end up wasted along the edges of triangles. As the quad has two triangles, the fragment blocks along the diagonal get rendered twice, which is inefficient. Besides that rendering a single triangle can have better local cache coherency.
> While the performance difference between a quad and single triangle might be tiny, it's enough that the standard approach nowadays is to go with the full-screen triangle, so we'll use it as well.

**Comment by ricardomatias** [comment]
@hamoid Yes, this would be only for optimization purposes.

**Comment by ricardomatias** [comment]
Closed due to the uncertainty around it giving a performance improvement

**Pull request closed without merging**
