### PR TITLE
add feature DrawRate

### PR DESCRIPTION
**Pull request by CodeCox**
Feature Drawrate() is an extension that allows finer control of the draw loop between the extremes of `AUTOMATIC` and `MANUAL` presentation modes.

This is under active development. It currently works for the base general case i.e. `DRAWRATE` and one special case viz. `MINIMISE`.

The ffg. key issues still need discussion/resolution. 
- The context of the coroutine. (`program.launch` is problematic and `GlobalScope.launch` is not recommended.)
- Special Case `UNFOCUS`. (use case needs detailing)
- Special Case `SIZE`. (use case needs detailing)

(@edwinRNDR Do you want me to initiate this discussion on the Slack-Development Channel or here?)

I will attach some documentation and example code to this PR for now (it will be the basis of what goes into the Guide when `Dokgen` becomes available to collaborators!)

P.S. This requires v0.3.31 at minimum.

### CODE REVIEW

**Comment by CodeCox** [comment]
This is USAGE documentation -

# DrawRate Extension

This configurable feature supports creative use of the Draw() loop. 
It also has a utilitarian purpose in that it enables a high-level means of managing consumption of system resources(CPU, GPU, Memory).

Blurb on `Presentation Control` from the Guide
> The default mode is automatic presentation, the draw method is called as often as possible. The other mode is manual presentation, in which it is the developer's responsibility to request draw to be called.

This feature supports finer control between `PresentationMode.AUTOMATIC` and `PresentationMode.MANUAL`.
It has a base `DrawRate` config that applies to the draw loop generally. 
Additionally, further special cases may be configured(currently, special case 'Minimise' is supported).

NB! Refrain from using presentation control modes 'AUTOMATIC' and 'MANUAL' within your app when this feature is `enabled` because it may cause contra-indications.  
 
## DrawRate
### Usage

```kotlin
val dcDrawRate = DrawConfig("myDrawRate", true, 200L)

extend(DrawRate()) {
    drawRate = dcDrawRate
}
```   

The config has 3 settings
- `id` : any string
- `enable` : true or false
- `delay duration` : a value greater than 0 i.e. between MINDELAY(1L) and MAXDELAY(Long.MAX_VALUE)

Subsequently the draw rate can also be toggled at runtime using the keyboard viz.
`<CTRL_SPACEBAR>`. (The drawing window must be active to receive keyboard input.)



#### Optional runtime config
Further control is supported at runtime e.g.
```
if (seconds.toInt() % 20 == 0)
    dcDrawRate.duration = 1L
if (seconds.toInt() % 20 == 10)
    dcDrawRate.duration = 225L
```
     
       
## Window Event - Special Case 1 
Some window events may cause the width and/or height to be 0 e.g. MINIMISE or SIZE. 
In this case the drawing window is not visible. 
In this situation it may make sense to pause the draw loop. 
(Or to reduce the frequency of the draw())

```kotlin
val dcMinimiseRate = DrawConfig("myMinimmiseRate", true, MAXDELAY)

extend(DrawRate()) {
    drawRate = dcMinimiseRate
}
```   

It has the same 3 config settings as DrawRate
- `id` : any string
- `enable` : true or false
- `delay duration` : a value greater than 0 i.e. between MINDELAY(1L) and MAXDELAY(Long.MAX_VALUE). 
MAXDELAY will effectively pause the draw loop. 

This action is triggered by a window `SIZE` event. It only goes into effect when the width or height is 0. 
A window 'RESTORE' event resumes the prior draw frequency. 
 
 
## Window Event - Special Case 2
### UNFOCUS - ToDo

**Comment by CodeCox** [comment]
This is example code -
```
import org.openrndr.application
import org.openrndr.color.ColorRGBa
import org.openrndr.extensions.DrawConfig
import org.openrndr.extensions.DrawRate
import org.openrndr.extensions.MAX_DELAY

fun main() = application {
    configure {
        title = "Color Perception based on DrawRate"
    }
    program {
        /* test cases
        1. no user config, ext defaults
        2. partial user config, partial ext defaults
        3. user config
        4. runtime config
         */
        val dcDrawRate = DrawConfig("myDrawRate", false, 200L)
        val dcMinimiseRate = DrawConfig("myMinimiseRate", true, 400L)
        extend(DrawRate()) {
            drawRate = dcDrawRate
            minimiseRate = dcMinimiseRate
        }

        var toggle = false
        extend {
            val dbgStart = seconds   //debug

            toggle = !toggle
            if (toggle)
                drawer.fill = ColorRGBa.BLUE
            else
                drawer.fill = ColorRGBa.RED
            drawer.circle(width / 2.0, height / 2.0, 200.0)

            // DrawRate runtime config - REMOVE COMMENTS TO TEST!
            /*
            if (seconds.toInt() % 20 == 0)
                dcDrawRate.duration = 1L
            if (seconds.toInt() % 20 == 10)
                dcDrawRate.duration = 225L
            */
            println("$dbgStart-$seconds") //debug
        }
    }
}
```

**Comment by CodeCox** [comment]
More contextual info that is pertinent for the forthcoming discussion on `Size` and `Unfocus`

The `Minimise` use case is a convenient reference point. It is just one of the outcomes of a window resizing event. It can be identified as when x-width AND y-height of the drawing window are both 0. In the implementation, a `MINIMISE` window event triggers the action for the `DrawRateConfig()` associated with this case. Subsequently, a `RESTORE` window event cancels this action. Importantly, (on Windows 10) the ffg. sequence of window events is received by the listeners in the application

_(The WindowEventInfo for each message below is not required here - you can ignore for now - it will be useful when considering `Size` and `Unfocus` later.)_
___
**A `Minimise` user action triggers the ffg msg's**

SIZE msg
```
 this = {DrawRate$setup$7@1793} "Function1<org.openrndr.WindowEvent, kotlin.Unit>"
it = {WindowEvent@1797} 
 type = {WindowEventType@1828} "RESIZED"
 position = {Vector2@1829} "Vector2(x=-21333.333333333332, y=-21333.333333333332)"
 size = {Vector2@1830} "Vector2(x=0.0, y=0.0)"
 focused = true
```
 UNFOCUS msg
```
 this = {DrawRate$setup$5@1834} "Function1<org.openrndr.WindowEvent, kotlin.Unit>"
it = {WindowEvent@1836} 
 type = {WindowEventType@1838} "FOCUSED"
 position = {Vector2@1839} "Vector2(x=0.0, y=0.0)"
 size = {Vector2@1840} "Vector2(x=0.0, y=0.0)"
 focused = false
```
 MINIMISE msg
```
 this = {DrawRate$setup$3@1844} "Function1<org.openrndr.WindowEvent, kotlin.Unit>"
it = {WindowEvent@1846} 
 type = {WindowEventType@1850} "MINIMIZED"
 position = {Vector2@1851} "Vector2(x=0.0, y=0.0)"
 size = {Vector2@1851} "Vector2(x=0.0, y=0.0)"
 focused = false
```

**Subsequently, a `Restore` user action triggers the ffg msg's**

 SIZE msg
```
 this = {DrawRate$setup$7@1793} "Function1<org.openrndr.WindowEvent, kotlin.Unit>"
it = {WindowEvent@1991} 
 type = {WindowEventType@1828} "RESIZED"
 position = {Vector2@1994} "Vector2(x=320.0, y=120.0)"
 size = {Vector2@1995} "Vector2(x=640.0, y=480.0)"
 focused = true
```
 FOCUS msg
```
 this = {DrawRate$setup$6@1998} "Function1<org.openrndr.WindowEvent, kotlin.Unit>"
it = {WindowEvent@2000} 
 type = {WindowEventType@1838} "FOCUSED"
 position = {Vector2@2002} "Vector2(x=0.0, y=0.0)"
 size = {Vector2@2003} "Vector2(x=0.0, y=0.0)"
 focused = true
```
 RESTORE msg
```
 this = {DrawRate$setup$4@2006} "Function1<org.openrndr.WindowEvent, kotlin.Unit>"
it = {WindowEvent@2008} 
 type = {WindowEventType@2010} "RESTORED"
 position = {Vector2@1851} "Vector2(x=0.0, y=0.0)"
 size = {Vector2@1851} "Vector2(x=0.0, y=0.0)"
 focused = true
```

**Comment by CodeCox** [comment]
**_ISSUE RE:_  the `Size` use case**

Another x-width and y-height sizing change seems relevant i.e. when x-width OR y-height is 0.  This is possible when config  `windowResizable = true`. We need to consider the ffg.
- Do we need to cater for this case?
- If yes, then should it use the `Mimimise` DrawRateConfig i.e. the action is identical to the `Minimise` use case?
- Or should it have a separate `Size` DrawRateConfig. Also why would the `Size` use case action be different? 
- The implementation would have to use the 'SIZE' window event to trigger this action. But this is a bit tricky for 2 reasons
  1. Only one trigger i.e.`SIZE` for starting AND cancelling this action.  
  2. It needs to be distinguished from the `SIZE` in the sequence of window events that are generated for the `Minimise` use case, otherwise intercepting those would result in duplication conflicts. 

For the both of the above the WindowEventInfo has to be checked for x and y values that uniquely identify this case, and cancelling this action requires knowledge of the previous state(which will have to be saved).

___
This is the smallest widow size I managed to get on WIndows 10 i.e. x=120, y=0. 
_(Is x=0 just a theoretical concern?)_  

SIZE msg
```
this = {DrawRate$setup$7@1798} "Function1<org.openrndr.WindowEvent, kotlin.Unit>"
it = {WindowEvent@1799} 
 type = {WindowEventType@1834} "RESIZED"
 position = {Vector2@1835} "Vector2(x=320.0, y=120.0)"
 size = {Vector2@1836} "Vector2(x=120.0, y=0.0)"
 focused = true
```

**Comment by CodeCox** [comment]
**_ISSUE RE:_ coroutine scope**

This has to do with the requirement that `launch()` must now have a scope. The most recent and authoritative article I came across on this topic is https://medium.com/@elizarov/structured-concurrency-722d765aa952 .
- `GlobalScope` is discouraged because it creates a top-level coroutine for the lifespan of the main application. A local `CoroutineScope` is preferred because it has the benefits of a restricted lifespan. 
- The PR code is using `GlobalScope` - this is not ideal but it is not overly problematic, since the `DrawRate` implementation is intended to exist for the lifespan of the application (unlike a resource request, for example). Worst case is sending a few additional `requestDraw()` msgs before the `jvm` tidies up and terminates.
- The `Program.launch` scope seems a natural `parent` but I suspect it uses a `CoroutineScope` rather than a `SupervisorScope` (these have a different `parent/child` relationships). I think this is the source of the conflict with my extensive use of `cancel`. _(I wanted to confirm this in the core code but the going gets hairy very early so I abandoned this line of inquiry since it won't necessarily solve the issue)_
- I'm looking into the option of creating a local `CoroutineScope/SupervisorScope` specifically for this extension to help ensure a clean and timely exit. It does makes sense to manage this locally within the `DrawRate` extension.

**Comment by edwinRNDR** [comment]
Do we need to do anything to support your UNFOCUSED case?

**Comment by CodeCox** [comment]
Yes ... it would help if I could distinguish between the **_UNFOCUS_-_FOCUS_** msgs in the `Unfocus` use case from the same msgs in the `Minimise` use case sequence i.e SIZE/**_UNFOCUS_**/MINIMISE- SIZE/**_FOCUS_**/RESTORE.

I'm guessing that `size` in `WindowEventInfo` is not being populated correctly because it is always `(0,0)` ?  I'm thinking `size` should be `(width,height)` and therefore (0,0) in the `Minimise use case  and `(n>0, n>0)` in the `Unfocused` use case. Are you passing thru whatever data you get from the windows system? Please check.

**Comment by CodeCox** [comment]
Development is now complete for this PR.  

It has only been tested on Windows 10 because thats all that I have available. Due diligence is still required on MacOS and LInux to ensure coroutine and window behaviour is as expected - however problems are not envisaged.

Updating the Guide and Examples is postponed until Dokgen becomes available to contributors.

**Comment by edwinRNDR** [comment]
This seems to work for me, also on macOS and Ubuntu. I do have some remarks and questions about the interface (and I am sorry to bring them up this late after your initial PR) 

What are the reasons for having singleton configuration objects? From what I can see it would be more convenient to have configuration properties as part of the extension, where they can be easier found through the IDE's type-completion.

Can the rate be configured in frames per second instead of milliseconds? I am asking this because I usually get the question "How do I set OPENRNDR's frame rate?"

I think the default configuration should be set to active, with the rate set at 60 FPS for normal modes and maybe 0 or 1 FPS for unfocused and minimized modes.

**Comment by CodeCox** [comment]
No worries - the break has help create some distance between me the code so I can now look at it with fresh eyes. 

**Interface**
A `Producer-Consumer` design kinda seemed to be a natural fit. So I had looked into implementing a `Actor` type interface. However, `Actor` in Kotlin is still 'unstable' with no clear future plans. Also, it was 'overkill' for the issue so I couldn't justify the more complex code implementation. But I retained some aspects from this design-pattern (i.e the sealed class singletons would have been messages!) so that we still have this option in the future (but only if this piece of functionality grows significantly).

Regarding your point about `configuration properties` -  I had consciously decided to not have the singletons as part of the extension properties to `simplify` the user interface, especially the runtime configuration of the delay. But, at that time I was heavily invested in the `Actor` design-pattern - so I'd be happy to revisit if you sketch out how you see this config within the extension framework (you have seen some of my earlier implementations of this which I thought were rather laboured)? 

**FPS**
I also think `FPS` would be a better way of thinking about the draw rate - `delay` has too many other connotations. However, a true `FPS` implementation is out of scope for me at the moment. I'm not a pedant so I'm happy to marry these two positions i.e. the user interface is `FPS` while the implementation remains `delay` - I reckon a simple `map` function makes trivial work of translating `fps` to `millis`. But this approach needs to come with disclaimers so we don't mislead our users - we need to spell it out in the documentation. Do you want me to explore this?

**Default config**
I was thinking that the various configs needed to be intentionally activated when desired. But I suppose adding the extension is intention enough! I will set the defaults as per your feedback - they make sense.

**Comment by CodeCox** [comment]
Hi @edwinRNDR

I'm not seeing any movement - so what's the status on this PR? 

I'm thinking that I'm done with this iteration ... but maybe you are waiting on me?

Let me know - thanks.

**Pull request closed without merging**
