### PR TITLE
Use buildSrc to deduplicate build logic

### PR DESCRIPTION
**Pull request by Vechro**
Adds two "convention" plugins to buildSrc. It appears you can just add a build script there and use it as a plugin in your project. This turns out to be a more flexible approach than trying to contain all the logic in the root build.gradle.
This enables us to remove all repetitive logic in build scripts that use the convention plugins.

What I removed:
We were depending on kotlin-reflect in tests for some reason. The tests seem to run fine without it.
I removed any remaining dependencies on openrndr-core, as it's just a collection of tests now and doesn't include any functionality.
For some reason we were compiling every project with the compiler flag `-Xuse-experimental=kotlinx.coroutines.InternalCoroutinesApi` but it didn't seem like we were actually making use of it. So I removed it.

To use version catalogs in buildSrc, it was necessary to migrate ours to `/gradle/libs.versions.toml`.
Dokka, nebula-release and kotlinx.serialization have also now been added to version catalogs.

Publishing logic could also be moved to convention plugins, but I know better than to attempt that.

### CODE REVIEW

**Comment by hamoid** [comment]
How did you dare? Amazing! :-)

Bonus points for the branch name XD

**Comment by Vechro** [comment]
By pure coincidence, I discovered this [incredible post on stackoverflow](https://stackoverflow.com/a/71892685/17977931) that documents the whole process of using convention plugins. I realized we could make use of this to move logic away from the root groovy build script without having to convert the whole file to kotlin.

**Comment by hamoid** [comment]
Thank you for that stackoverflow link! I find it clearer than the official gradle docs.

**Comment by hamoid** [comment]
Yay! image

**Pull request merged**
