### PR TITLE
Added basic rounded rectangles using contour lineTo/curveTo

### PR DESCRIPTION
**Pull request by reinvdwoerd**
Methods like area() are not implemented yet, and perhaps the code shouldn't be duplicated between CompositionDrawer and Drawer...

### CODE REVIEW

**Comment by edwinRNDR** [comment]
I think this is good code, and I will use it. But I think this has to be part of ORX instead. It is imo not core functionality and I think it would do a great job serving as a seed for a library of shape generators.

**Comment by hamoid** [comment]
What about n-gon? And n-gon with rounded corners? :)

**Comment by reinvdwoerd** [comment]
Yeah that’s nice too

**Comment by edwinRNDR** [comment]
Added parts of this to orx-shapes https://github.com/openrndr/orx/tree/master/orx-shapes/src/main/kotlin

**Comment by reinvdwoerd** [comment]
It's alive!

**Pull request closed without merging**
